version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
